# Generated by Django 5.2.15 on 2026-06-30 12:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Индекс уровня (i)')),
                ('price', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Цена уровня')),
                ('side', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4, verbose_name='Сторона')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('pending', 'Размещается'), ('open', 'Открыт ордер'), ('filled', 'Исполнен')], default='free', max_length=8, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Уровень сетки',
                'verbose_name_plural': 'Уровни сетки',
                'ordering': ['strategy', 'index'],
            },
        ),
        migrations.CreateModel(
            name='GridStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('inst_id', models.CharField(default='BTC-USDT', max_length=40, verbose_name='Инструмент (instId)')),
                ('inst_type', models.CharField(default='SPOT', max_length=10, verbose_name='Тип инструмента')),
                ('td_mode', models.CharField(default='cash', max_length=10, verbose_name='Режим торговли (tdMode)')),
                ('p_max', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Верхняя цена (Pmax)')),
                ('p_min', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Нижняя цена (Pmin)')),
                ('levels', models.PositiveIntegerField(default=10, verbose_name='Число уровней (N)')),
                ('grid_type', models.CharField(choices=[('arithmetic', 'Арифметическая (равномерная)'), ('geometric', 'Геометрическая (логарифмическая)')], default='arithmetic', max_length=12, verbose_name='Тип сетки')),
                ('order_size', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Объём ордера (база)')),
                ('tick_sz', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Шаг цены (tickSz)')),
                ('lot_sz', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Шаг объёма (lotSz)')),
                ('min_sz', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Мин. объём (minSz)')),
                ('stop_loss_enabled', models.BooleanField(default=True, verbose_name='Стоп-лосс включён')),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=12, help_text='Если пусто — используется Pmin.', max_digits=30, null=True, verbose_name='Цена стоп-лосса')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готова (уровни рассчитаны)'), ('running', 'Запущена'), ('stopped', 'Остановлена'), ('emergency', 'Аварийный выход (stop-loss)')], default='draft', max_length=12, verbose_name='Статус')),
                ('is_demo', models.BooleanField(default=True, verbose_name='Демо-режим')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Стратегия (сетка)',
                'verbose_name_plural': 'Стратегии (сетки)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GridOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_ord_id', models.CharField(db_index=True, max_length=64, verbose_name='Клиентский ID (clOrdId)')),
                ('ord_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID ордера OKX (ordId)')),
                ('side', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4, verbose_name='Сторона')),
                ('price', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Цена')),
                ('size', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Объём')),
                ('state', models.CharField(choices=[('pending', 'Отправляется'), ('live', 'Активен'), ('partially_filled', 'Частично исполнен'), ('filled', 'Исполнен'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Состояние')),
                ('filled_size', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30, verbose_name='Исполнено')),
                ('avg_px', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Средняя цена исполн.')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Сырой ответ OKX')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='grid.gridlevel', verbose_name='Уровень')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='grid.gridstrategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Ордер сетки',
                'verbose_name_plural': 'Ордера сетки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gridlevel',
            name='active_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='grid.gridorder', verbose_name='Активный ордер'),
        ),
        migrations.AddField(
            model_name='gridlevel',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_levels', to='grid.gridstrategy', verbose_name='Стратегия'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_qty', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30, verbose_name='Объём позиции (база)')),
                ('avg_price', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30, verbose_name='Средневзвешенная цена (VWAP)')),
                ('realized_pnl', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30, verbose_name='Реализованная прибыль')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='grid.gridstrategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Позиция (VWAP)',
                'verbose_name_plural': 'Позиции (VWAP)',
            },
        ),
        migrations.CreateModel(
            name='StrategyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR')], default='info', max_length=10, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='grid.gridstrategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Лог стратегии',
                'verbose_name_plural': 'Логи стратегии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID сделки (tradeId)')),
                ('side', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4, verbose_name='Сторона')),
                ('fill_price', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Цена исполнения')),
                ('fill_size', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Объём исполнения')),
                ('fee', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30, verbose_name='Комиссия')),
                ('fee_ccy', models.CharField(blank=True, max_length=20, verbose_name='Валюта комиссии')),
                ('ts', models.DateTimeField(verbose_name='Время сделки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Записана')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='grid.gridorder', verbose_name='Ордер')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='grid.gridstrategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Сделка (исполнение)',
                'verbose_name_plural': 'Сделки (исполнения)',
                'ordering': ['-ts'],
            },
        ),
        migrations.AddConstraint(
            model_name='gridorder',
            constraint=models.UniqueConstraint(fields=('strategy', 'cl_ord_id'), name='uniq_strategy_clordid'),
        ),
        migrations.AddConstraint(
            model_name='gridlevel',
            constraint=models.UniqueConstraint(fields=('strategy', 'index'), name='uniq_strategy_level_index'),
        ),
    ]
