# Generated by Django 5.2.15 on 2026-06-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridstrategy',
            name='runner_pid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PID рабочего цикла'),
        ),
        migrations.AddField(
            model_name='gridstrategy',
            name='runner_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Цикл запущен'),
        ),
    ]
