# Generated by Django 5.2.15 on 2026-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_gridstrategy_runner_pid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gridstrategy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Стратегия', 'verbose_name_plural': 'Стратегии'},
        ),
        migrations.AddField(
            model_name='gridstrategy',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры стратегии'),
        ),
        migrations.AddField(
            model_name='gridstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('grid', 'Сетка (Grid)'), ('dca', 'Усреднение (DCA)'), ('trend', 'Следование за трендом (Trend)'), ('arbitrage', 'Арбитраж (Arbitrage)'), ('scalping', 'Скальпинг (Scalping)')], default='grid', max_length=12, verbose_name='Тип стратегии'),
        ),
        migrations.AlterField(
            model_name='gridstrategy',
            name='levels',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Число уровней (N)'),
        ),
        migrations.AlterField(
            model_name='gridstrategy',
            name='order_size',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Объём ордера (база)'),
        ),
        migrations.AlterField(
            model_name='gridstrategy',
            name='p_max',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Верхняя цена (Pmax)'),
        ),
        migrations.AlterField(
            model_name='gridstrategy',
            name='p_min',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Нижняя цена (Pmin)'),
        ),
        migrations.AlterField(
            model_name='gridstrategy',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готова'), ('running', 'Запущена'), ('stopped', 'Остановлена'), ('emergency', 'Аварийный выход (stop-loss)')], default='draft', max_length=12, verbose_name='Статус'),
        ),
    ]
