# Generated by Django 5.2.15 on 2026-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_alter_gridstrategy_options_gridstrategy_params_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.CharField(max_length=40, unique=True, verbose_name='Инструмент (instId)')),
                ('inst_type', models.CharField(default='SPOT', max_length=10, verbose_name='Тип')),
                ('base_ccy', models.CharField(blank=True, max_length=20, verbose_name='Базовая валюта')),
                ('quote_ccy', models.CharField(blank=True, max_length=20, verbose_name='Котируемая валюта')),
                ('tick_sz', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Шаг цены')),
                ('lot_sz', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Шаг объёма')),
                ('min_sz', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Мин. объём')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='Состояние')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Инструмент (пара)',
                'verbose_name_plural': 'Инструменты (пары)',
                'ordering': ['inst_id'],
            },
        ),
    ]
