# Generated by Django 5.2.15 on 2026-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='active',
            field=models.BooleanField(default=True, help_text='Показывать пару в мастере создания стратегии.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='state',
            field=models.CharField(blank=True, max_length=20, verbose_name='Состояние (биржа)'),
        ),
    ]
