# Generated by Django 5.2.15 on 2026-07-03 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('equity', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Эквити, USDT')),
            ],
            options={
                'verbose_name': 'Снимок эквити',
                'verbose_name_plural': 'Снимки эквити',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='RiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Риск-контроль включён')),
                ('max_position_per_pair', models.DecimalField(blank=True, decimal_places=12, help_text='Потолок вложенного в одну пару (позиция + активные buy-ордера).', max_digits=30, null=True, verbose_name='Макс. позиция на пару, USDT')),
                ('max_total_exposure', models.DecimalField(blank=True, decimal_places=12, help_text='Суммарный потолок вложенного по всем стратегиям.', max_digits=30, null=True, verbose_name='Макс. общая экспозиция, USDT')),
                ('daily_loss_limit', models.DecimalField(blank=True, decimal_places=12, help_text='При падении эквити за день на эту сумму — аварийная остановка всех.', max_digits=30, null=True, verbose_name='Дневной лимит убытка, USDT')),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=2, help_text='При просадке эквити от пика на этот % — аварийная остановка всех.', max_digits=6, null=True, verbose_name='Макс. просадка, %')),
                ('blacklist', models.TextField(blank=True, help_text='Монеты или пары через запятую/пробел (напр. DOGE, SHIB-USDT) — торговля запрещена.', verbose_name='Чёрный список')),
                ('fee_pct', models.DecimalField(decimal_places=4, default=Decimal('0.1'), max_digits=6, verbose_name='Комиссия (для проверки шага), %')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлены')),
            ],
            options={
                'verbose_name': 'Риск-настройки',
                'verbose_name_plural': 'Риск-настройки',
            },
        ),
    ]
