# Generated by Django 5.2.15 on 2026-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_equitysnapshot_risksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridstrategy',
            name='mode',
            field=models.CharField(choices=[('demo', 'Демо (тест)'), ('live', 'Реал')], default='demo', help_text='demo — тестовая торговля; live — реальная (боевые ключи).', max_length=5, verbose_name='Режим'),
        ),
    ]
