# Generated by Django 5.2.15 on 2026-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0008_gridstrategy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridstrategy',
            name='desired_state',
            field=models.CharField(choices=[('run', 'Запустить'), ('stop', 'Остановить')], default='stop', max_length=4, verbose_name='Желаемое состояние'),
        ),
        migrations.AddField(
            model_name='gridstrategy',
            name='last_error',
            field=models.CharField(blank=True, max_length=300, verbose_name='Последняя ошибка'),
        ),
        migrations.AddField(
            model_name='gridstrategy',
            name='last_tick_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний тик'),
        ),
    ]
