# Generated by Django 5.2.15 on 2026-07-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0009_gridstrategy_desired_state_gridstrategy_last_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сервис (API)',
                'verbose_name_plural': 'Сервис (API)',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='gridstrategy',
            name='mode',
            field=models.CharField(choices=[('demo', 'Демо'), ('live', 'Реал')], default='demo', help_text='demo — тестовая торговля; live — реальная (боевые ключи).', max_length=5, verbose_name='Режим'),
        ),
    ]
