# Generated by Django 5.2.15 on 2026-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0010_service_alter_gridstrategy_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridstrategy',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готова'), ('running', 'Запущена'), ('stopped', 'Остановлена'), ('emergency', 'Аварийный выход (stop-loss)'), ('archived', 'Архив')], default='draft', max_length=12, verbose_name='Статус'),
        ),
    ]
