# Generated by Django 5.2.15 on 2026-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0011_alter_gridstrategy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridstrategy',
            name='leverage',
            field=models.PositiveIntegerField(default=1, help_text='1 = без плеча (спот). Действует только с маржой (isolated/cross). С плечом ×N риск и экспозиция в N раз больше маржи, появляется ликвидация.', verbose_name='Плечо'),
        ),
        migrations.AlterField(
            model_name='gridstrategy',
            name='td_mode',
            field=models.CharField(choices=[('cash', 'Наличный / спот (cash)'), ('isolated', 'Изолированная маржа (isolated)'), ('cross', 'Кросс-маржа (cross)')], default='cash', help_text='cash — спот без плеча; isolated/cross — маржа с плечом (для деривативов).', max_length=10, verbose_name='Режим маржи (tdMode)'),
        ),
    ]
