# Generated by Django 5.2.15 on 2026-07-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0013_cleanup_risksettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='Последний heartbeat')),
                ('strategies_count', models.IntegerField(default=0, verbose_name='Количество стратегий')),
                ('running_count', models.IntegerField(default=0, verbose_name='Запущено стратегий')),
                ('stopped_count', models.IntegerField(default=0, verbose_name='Остановлено стратегий')),
                ('orders_processed', models.IntegerField(default=0, verbose_name='Ордеров обработано')),
                ('cycles_completed', models.BigIntegerField(default=0, verbose_name='Циклов завершено')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('is_running', models.BooleanField(default=False, verbose_name='Воркер работает')),
            ],
            options={
                'verbose_name': 'Статус воркера',
                'verbose_name_plural': 'Статус воркера',
                'managed': False,
            },
        ),
    ]
