# Generated by Django 5.2.15 on 2026-07-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0014_workerstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerstatus',
            options={'verbose_name': 'Статус воркера', 'verbose_name_plural': 'Статус воркера'},
        ),
    ]
